package com.alex.weatherapp.MapsFramework.MapVisuals.Markers;

import com.alex.weatherapp.MapsFramework.EntityGeneral.MapEntity;
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.Marker;

/**
 * Created by Alex on 06.11.2015.
 */

/**
 * All information is within GMap's marker. Data entity, on contrary, carries all information,
 * needed to generate this marker. This entity is generated by projector. Wraps GMap's marker
 * methods
 */
public class PlaceMarker extends MapEntity {
    public PlaceMarker(){
        mUnderlyingMarker = null;
    }
    public PlaceMarker(Marker marker){
        mUnderlyingMarker = marker;
    }
    public Marker getMarker(){
        return mUnderlyingMarker;
    }
    public void setMarker(Marker marker){
        mUnderlyingMarker = marker;
    }
    public String getTitle(){
        return mMarkerTitle;
    }
    public void setMarkerTitle(String title){
        mMarkerTitle = title;
    }
    public String getID(){
        if (null == mUnderlyingMarker){
            return  "";
        }
        return mUnderlyingMarker.getId();
    }
    public LatLng getPosition(){
        return mUnderlyingMarker.getPosition();
    }

    Marker mUnderlyingMarker;
    /** we can't acces Marker instance on Worker thread, so store it here */
    private String mMarkerTitle;

}
